"""Static published site (Eleventy) + sitemap connector.

The public sitemap is generated by the static site build
(unicorniohater-static/scripts/sitemap.mjs), NOT by WordPress directly —
this connector reads that surface.
"""

from __future__ import annotations

import re
from html.parser import HTMLParser
from typing import Any
from urllib.parse import urljoin, urlparse
from xml.etree import ElementTree as ET

from ..config import Config
from .base import ConnectorError, HttpClient

_SITEMAP_NS = "{http://www.sitemaps.org/schemas/sitemap/0.9}"


class PageSnapshot:
    """Deterministic snapshot of one rendered HTML page."""

    __slots__ = ("url", "status_code", "title", "meta_description", "canonical",
                 "meta_robots", "h1", "h2s", "images", "links", "body_text", "html")

    def __init__(self, url: str, status_code: int):
        self.url = url
        self.status_code = status_code
        self.title = ""
        self.meta_description = ""
        self.canonical = ""
        self.meta_robots = ""
        self.h1: list[str] = []
        self.h2s: list[str] = []
        self.images: list[dict[str, str]] = []
        self.links: list[str] = []
        # Text from <main> or <article>, excluding layout and executable nodes.
        # This is deliberately kept separate from the raw HTML for content analysis.
        self.body_text = ""
        self.html = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "url": self.url,
            "status_code": self.status_code,
            "title": self.title,
            "meta_description": self.meta_description,
            "canonical": self.canonical,
            "meta_robots": self.meta_robots,
            "h1_count": len(self.h1),
            "h2_count": len(self.h2s),
            "image_count": len(self.images),
            "link_count": len(self.links),
            "body_word_count": len(self.body_text.split()),
        }


class _PageParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.title_parts: list[str] = []
        self.in_title = False
        self.in_h1 = False
        self.h1_parts: list[str] = []
        self.in_h2 = False
        self.current_h2_parts: list[str] = []
        self.h2s: list[str] = []
        self.meta_description = ""
        self.canonical = ""
        self.meta_robots = ""
        self.images: list[dict[str, str]] = []
        self.links: list[str] = []
        self.body_parts: list[str] = []
        self.content_depth = 0
        self.ignore_depth = 0

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr = {k.lower(): (v or "") for k, v in attrs}
        if tag in {"main", "article"}:
            self.content_depth += 1
        elif tag in {"script", "style", "noscript", "template", "nav", "footer", "aside"}:
            self.ignore_depth += 1
        if tag == "title":
            self.in_title = True
        elif tag == "h1":
            self.in_h1 = True
        elif tag == "h2":
            self.in_h2 = True
            self.current_h2_parts = []
        elif tag == "meta":
            name = attr.get("name", "").lower()
            if name == "description":
                self.meta_description = attr.get("content", "")
            elif name == "robots":
                self.meta_robots = attr.get("content", "")
        elif tag == "link":
            rel = attr.get("rel", "").lower()
            if "canonical" in rel.split():
                self.canonical = attr.get("href", "")
        elif tag == "img":
            self.images.append(
                {"src": attr.get("src", ""), "alt": attr.get("alt", ""),
                 "width": attr.get("width", ""), "height": attr.get("height", ""),
                 "loading": attr.get("loading", "")}
            )
        elif tag == "a":
            href = attr.get("href", "")
            if href:
                self.links.append(href)

    def handle_endtag(self, tag: str) -> None:
        if tag in {"main", "article"} and self.content_depth:
            self.content_depth -= 1
        elif tag in {"script", "style", "noscript", "template", "nav", "footer", "aside"} and self.ignore_depth:
            self.ignore_depth -= 1
        if tag == "title":
            self.in_title = False
        elif tag == "h1":
            self.in_h1 = False
        elif tag == "h2":
            self.in_h2 = False
            heading = " ".join(self.current_h2_parts).strip()
            if heading:
                self.h2s.append(heading)

    def handle_data(self, data: str) -> None:
        if self.in_title:
            self.title_parts.append(data)
        elif self.in_h1:
            self.h1_parts.append(data)
        elif self.in_h2:
            self.current_h2_parts.append(data)
        if self.content_depth and not self.ignore_depth:
            self.body_parts.append(data)


class StaticSiteClient:
    def __init__(self, config: Config, http: HttpClient | None = None):
        self.config = config
        self.http = http or HttpClient(timeout=config.http_timeout)

    # -- sitemap -------------------------------------------------------------

    def fetch_sitemap_index(self, url: str | None = None) -> list[str]:
        """Parse a <sitemapindex> and return the child sitemap URLs."""
        url = url or self.config.sitemap_url
        response = self.http.get(url)
        if response.status_code != 200:
            raise ConnectorError(f"sitemap index {url} returned HTTP {response.status_code}")
        return _parse_sitemap_urls(response.text, is_index=True)

    def fetch_sitemap(self, url: str) -> list[str]:
        """Parse a <urlset> and return the <loc> URLs."""
        response = self.http.get(url)
        if response.status_code != 200:
            raise ConnectorError(f"sitemap {url} returned HTTP {response.status_code}")
        return _parse_sitemap_urls(response.text, is_index=False)

    def all_sitemap_urls(self, sitemap_url: str | None = None) -> list[str]:
        """Resolve the whole sitemap tree into the final URL list."""
        urls: list[str] = []
        for child in self.fetch_sitemap_index(sitemap_url):
            resolved = urljoin(self.config.sitemap_url, child)
            urls.extend(self.fetch_sitemap(resolved))
        return urls

    # -- pages ---------------------------------------------------------------

    def fetch_page(self, url: str) -> PageSnapshot:
        response = self.http.get(url)
        snapshot = PageSnapshot(url=url, status_code=response.status_code)
        if response.status_code == 200:
            snapshot.html = response.text
            parser = _PageParser()
            try:
                parser.feed(response.text)
                parser.close()
            except Exception:  # broken HTML must not kill the audit
                pass
            snapshot.title = " ".join(parser.title_parts).strip()
            snapshot.meta_description = parser.meta_description.strip()
            snapshot.canonical = parser.canonical.strip()
            snapshot.meta_robots = parser.meta_robots.strip()
            snapshot.h1 = [" ".join(parser.h1_parts).strip()] if parser.h1_parts else []
            snapshot.h2s = parser.h2s
            snapshot.images = parser.images
            snapshot.links = parser.links
            snapshot.body_text = " ".join(parser.body_parts).strip()
        return snapshot

    # -- robots.txt ----------------------------------------------------------

    def fetch_robots(self, base_url: str | None = None) -> "RobotsRules":
        base = (base_url or self.config.static_site_url).rstrip("/")
        response = self.http.get(f"{base}/robots.txt")
        if response.status_code != 200:
            return RobotsRules(base=base, raw="", disallow=[], sitemaps=[])
        return RobotsRules.parse(base, response.text)

    def close(self) -> None:
        self.http.close()

    def __enter__(self) -> "StaticSiteClient":
        return self

    def __exit__(self, *exc: Any) -> None:
        self.close()


class RobotsRules:
    """Minimal robots.txt parser: Disallow rules + Sitemap directives."""

    def __init__(self, *, base: str, raw: str, disallow: list[str], sitemaps: list[str]):
        self.base = base
        self.raw = raw
        self.disallow = disallow
        self.sitemaps = sitemaps

    @classmethod
    def parse(cls, base: str, raw: str) -> "RobotsRules":
        disallow: list[str] = []
        sitemaps: list[str] = []
        for line in raw.splitlines():
            line = line.strip()
            if not line or line.startswith("#") or ":" not in line:
                continue
            field, _, value = line.partition(":")
            field = field.strip().lower()
            value = value.strip()
            if field == "disallow" and value:
                disallow.append(value)
            elif field == "sitemap":
                sitemaps.append(value)
        return cls(base=base, raw=raw, disallow=disallow, sitemaps=sitemaps)

    def is_blocked(self, url: str) -> bool:
        path = urlparse(url).path
        for rule in self.disallow:
            if rule == "/" and path != "/":
                return True
            if rule and path.startswith(rule):
                return True
        return False


def _parse_sitemap_urls(xml_text: str, *, is_index: bool) -> list[str]:
    try:
        root = ET.fromstring(xml_text)
    except ET.ParseError as exc:
        raise ConnectorError(f"invalid sitemap XML: {exc}") from exc
    tag = f"{_SITEMAP_NS}sitemap" if is_index else f"{_SITEMAP_NS}url"
    urls: list[str] = []
    for node in root.iter(tag):
        loc = node.find(f"{_SITEMAP_NS}loc")
        if loc is not None and loc.text and loc.text.strip():
            urls.append(loc.text.strip())
    return urls
