"""Static published site (Eleventy) + sitemap connector.

The public sitemap is generated by the static site build
(unicorniohater-static/scripts/sitemap.mjs), NOT by WordPress directly —
this connector reads that surface.
"""

from __future__ import annotations

import re
import gzip
import hashlib
from html.parser import HTMLParser
from typing import Any
from urllib.parse import urljoin, urlparse
from xml.etree import ElementTree as ET

from ..config import Config
from .base import ConnectorError, HttpClient

_SITEMAP_NS = "{http://www.sitemaps.org/schemas/sitemap/0.9}"


class PageSnapshot:
    """Deterministic snapshot of one rendered HTML page."""

    __slots__ = ("url", "status_code", "title", "meta_description", "canonical",
                 "meta_robots", "h1", "h2s", "images", "links", "body_text", "html")

    def __init__(self, url: str, status_code: int):
        self.url = url
        self.status_code = status_code
        self.title = ""
        self.meta_description = ""
        self.canonical = ""
        self.meta_robots = ""
        self.h1: list[str] = []
        self.h2s: list[str] = []
        self.images: list[dict[str, str]] = []
        self.links: list[str] = []
        # Text from <main> or <article>, excluding layout and executable nodes.
        # This is deliberately kept separate from the raw HTML for content analysis.
        self.body_text = ""
        self.html = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "url": self.url,
            "status_code": self.status_code,
            "title": self.title,
            "meta_description": self.meta_description,
            "canonical": self.canonical,
            "meta_robots": self.meta_robots,
            "h1_count": len(self.h1),
            "h2_count": len(self.h2s),
            "image_count": len(self.images),
            "link_count": len(self.links),
            "body_word_count": len(self.body_text.split()),
        }


class _PageParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.title_parts: list[str] = []
        self.in_title = False
        self.in_h1 = False
        self.h1_parts: list[str] = []
        self.in_h2 = False
        self.current_h2_parts: list[str] = []
        self.h2s: list[str] = []
        self.meta_description = ""
        self.canonical = ""
        self.meta_robots = ""
        self.images: list[dict[str, str]] = []
        self.links: list[str] = []
        self.body_parts: list[str] = []
        self.content_depth = 0
        self.ignore_depth = 0

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr = {k.lower(): (v or "") for k, v in attrs}
        if tag in {"main", "article"}:
            self.content_depth += 1
        elif tag in {"script", "style", "noscript", "template", "nav", "footer", "aside"}:
            self.ignore_depth += 1
        if tag == "title":
            self.in_title = True
        elif tag == "h1":
            self.in_h1 = True
        elif tag == "h2":
            self.in_h2 = True
            self.current_h2_parts = []
        elif tag == "meta":
            name = attr.get("name", "").lower()
            if name == "description":
                self.meta_description = attr.get("content", "")
            elif name == "robots":
                self.meta_robots = attr.get("content", "")
        elif tag == "link":
            rel = attr.get("rel", "").lower()
            if "canonical" in rel.split():
                self.canonical = attr.get("href", "")
        elif tag == "img":
            self.images.append(
                {"src": attr.get("src", ""), "alt": attr.get("alt", ""),
                 "width": attr.get("width", ""), "height": attr.get("height", ""),
                 "loading": attr.get("loading", "")}
            )
        elif tag == "a":
            href = attr.get("href", "")
            if href:
                self.links.append(href)

    def handle_endtag(self, tag: str) -> None:
        if tag in {"main", "article"} and self.content_depth:
            self.content_depth -= 1
        elif tag in {"script", "style", "noscript", "template", "nav", "footer", "aside"} and self.ignore_depth:
            self.ignore_depth -= 1
        if tag == "title":
            self.in_title = False
        elif tag == "h1":
            self.in_h1 = False
        elif tag == "h2":
            self.in_h2 = False
            heading = " ".join(self.current_h2_parts).strip()
            if heading:
                self.h2s.append(heading)

    def handle_data(self, data: str) -> None:
        if self.in_title:
            self.title_parts.append(data)
        elif self.in_h1:
            self.h1_parts.append(data)
        elif self.in_h2:
            self.current_h2_parts.append(data)
        if self.content_depth and not self.ignore_depth:
            self.body_parts.append(data)


class StaticSiteClient:
    def __init__(self, config: Config, http: HttpClient | None = None,
                 cache_store: Any | None = None, budget: Any | None = None):
        self.config = config
        self.http = http or HttpClient(timeout=config.http_timeout, budget=budget)
        # cache_store compartilhado (RunContext.storage()): evita abrir um
        # Storage + schema + migração + commit por request HTTP. Se ausente,
        # o client é dono de uma conexão lazily criada (e fechada em close()).
        self.cache_store = cache_store
        self._own_store = None
        # Guard SSRF: apenas hosts do próprio site; resolve DNS se configurado.
        from .url_guard import allowed_hosts_from_config
        self.allowed_hosts = allowed_hosts_from_config(config)
        self.ssrf_resolve = bool(getattr(config, "ssrf_resolve_dns", False))

    def validate_url(self, url: str) -> None:
        """Levanta UnsafeUrlError se a URL for insegura (SSRF)."""
        from .url_guard import validate_external_url
        validate_external_url(url, allowed_hosts=self.allowed_hosts,
                              resolve=self.ssrf_resolve)

    # -- sitemap -------------------------------------------------------------

    def fetch_sitemap_index(self, url: str | None = None) -> list[str]:
        """Parse a <sitemapindex> and return the child sitemap URLs."""
        url = url or self.config.sitemap_url
        response = self._cached_get(url, cache_body=True)
        if response.status_code != 200:
            raise ConnectorError(f"sitemap index {url} returned HTTP {response.status_code}")
        return _parse_sitemap_urls(response.text, is_index=True)

    def fetch_sitemap(self, url: str) -> list[str]:
        """Parse a <urlset> and return the <loc> URLs."""
        response = self._cached_get(url, cache_body=True)
        if response.status_code != 200:
            raise ConnectorError(f"sitemap {url} returned HTTP {response.status_code}")
        return _parse_sitemap_urls(response.text, is_index=False)

    def all_sitemap_entries(self, sitemap_url: str | None = None) -> list[tuple[str, str]]:
        """Resolve the sitemap tree into (url, lastmod) entries.

        `lastmod` ("" quando ausente) é o sinal de mudança de CONTEÚDO do sitemap:
        permite ao audit incremental detectar alterações em URLs que continuam
        presentes na lista (a lista de URLs sozinha não captura isso).
        """
        entries: list[tuple[str, str]] = []
        seen: set[str] = set()
        index_url = sitemap_url or self.config.sitemap_url
        for child in self.fetch_sitemap_index(index_url):
            resolved = urljoin(index_url, child)
            for loc, lastmod in self._fetch_sitemap_entries(resolved):
                if loc not in seen:
                    seen.add(loc)
                    entries.append((loc, lastmod))
        return entries

    def _fetch_sitemap_entries(self, url: str) -> list[tuple[str, str]]:
        response = self._cached_get(url, cache_body=True)
        if response.status_code != 200:
            raise ConnectorError(f"sitemap {url} returned HTTP {response.status_code}")
        return _parse_sitemap_entries(response.text, is_index=False)

    def _get_store(self):
        """Storage do cache: o compartilhado (RunContext) ou um próprio lazily."""
        if self.cache_store is not None:
            return self.cache_store
        if self._own_store is None:
            from ..storage.db import Storage
            self._own_store = Storage(self.config.sqlite_path)
        return self._own_store

    def _disk_path(self, url: str) -> str:
        import os
        base = getattr(self.config, "http_cache_dir", "./state/http_cache")
        return os.path.join(base, hashlib.sha256(url.encode()).hexdigest()[:32] + ".gz")

    def _disk_write(self, url: str, data: bytes) -> None:
        """Gravação ATÔMICA: escreve .tmp, fsync, os.replace (sem .gz parcial)."""
        import os
        path = self._disk_path(url)
        tmp = f"{path}.{os.getpid()}.tmp"
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(tmp, "wb") as fh:
                fh.write(data)
                fh.flush()
                os.fsync(fh.fileno())
            os.replace(tmp, path)
        except Exception:
            try:
                if os.path.exists(tmp):
                    os.remove(tmp)
            except Exception:
                pass
            # cache de disco é best-effort; nunca derrubar o fetch

    def _disk_clear(self, url: str) -> None:
        import os
        try:
            os.remove(self._disk_path(url))
        except Exception:
            pass

    def _max_bytes(self, cache_body: bool) -> int:
        attr = "max_sitemap_bytes" if cache_body else "max_page_bytes"
        try:
            return int(getattr(self.config, attr, 0) or 0)
        except Exception:
            return 0

    def _disk_read(self, url: str) -> bytes | None:
        path = self._disk_path(url)
        try:
            with open(path, "rb") as fh:
                return fh.read()
        except Exception:
            return None

    def _decompress(self, url: str, body: bytes) -> bytes | None:
        """Descomprime tolerante: .gz corrompido -> limpa cache e devolve None."""
        try:
            return gzip.decompress(body)
        except (gzip.BadGzipFile, OSError, EOFError):
            self._disk_clear(url)
            return None

    def _cached_get(self, url: str, *, cache_body: bool = True):
        """GET condicional com cache. `cache_body`:
        - True (sitemap/robots/recursos): guarda o corpo gzip no SQLite.
        - False (páginas): guarda só ETag/Last-Modified/content_hash no SQLite e o
          corpo gzip em ARQUIVO NO DISCO (evita inflar o SQLite com HTML de
          milhares de páginas). Em 304, reconstrói a resposta a partir do disco.
        """
        store = self._get_store()
        # Guard SSRF antes de qualquer fetch (sitemap ou página).
        self.validate_url(url)
        cached = store.get_http_cache(url)
        # GET condicional com teto de bytes em STREAMING (não baixa 500MB p/ RAM).
        merged: dict[str, str] = {}
        if (cached or {}).get("etag"):
            merged["If-None-Match"] = cached["etag"]
        if (cached or {}).get("last_modified"):
            merged["If-Modified-Since"] = cached["last_modified"]
        response = self.http.get_limited(url, max_bytes=self._max_bytes(cache_body),
                                         headers=merged)
        if response.status_code == 304:
            raw = None
            if cache_body:
                raw = (cached or {}).get("body")
            else:
                raw = self._disk_read(url)
            content = self._decompress(url, raw) if raw is not None else None
            if content is not None:
                response = type(response)(status_code=200, headers=response.headers,
                                          content=content)
                if self.http.budget is not None:
                    self.http.budget.hit("http_304")  # corpo reusado (não é chamada evitada)
            else:
                # 304 sem corpo (cache limpo) ou .gz corrompido: força um GET pleno.
                response = self.http.get_limited(url, max_bytes=self._max_bytes(cache_body))
        if response.status_code == 200:
            # (o limite de bytes é aplicado em streaming no get_limited acima)
            etag = response.headers.get("etag", "")
            last_modified = response.headers.get("last-modified", "")
            content_hash = hashlib.sha256(response.content).hexdigest()
            if cache_body:
                store.save_http_cache(url, etag=etag, last_modified=last_modified,
                                      status_code=200, body=gzip.compress(response.content),
                                      content_hash=content_hash)
            else:
                self._disk_write(url, gzip.compress(response.content))
                store.save_http_cache(url, etag=etag, last_modified=last_modified,
                                      status_code=200, body=None, content_hash=content_hash)
        return response

    def all_sitemap_urls(self, sitemap_url: str | None = None) -> list[str]:
        """Resolve the whole sitemap tree into the final URL list."""
        return [loc for loc, _ in self.all_sitemap_entries(sitemap_url)]

    def fetch_text(self, url: str) -> str:
        """Corpo de um recurso textual (ex.: marcador de build). Guard SSRF on."""
        return self._cached_get(url, cache_body=True).text

    # -- pages ---------------------------------------------------------------

    def fetch_page(self, url: str) -> PageSnapshot:
        # Corpo da página vai para cache de DISCO (separado do SQLite); no banco
        # só ETag/Last-Modified/content_hash.
        response = self._cached_get(url, cache_body=False)
        snapshot = PageSnapshot(url=url, status_code=response.status_code)
        if response.status_code == 200:
            snapshot.html = response.text
            parser = _PageParser()
            try:
                parser.feed(response.text)
                parser.close()
            except Exception:  # broken HTML must not kill the audit
                pass
            snapshot.title = " ".join(parser.title_parts).strip()
            snapshot.meta_description = parser.meta_description.strip()
            snapshot.canonical = parser.canonical.strip()
            snapshot.meta_robots = parser.meta_robots.strip()
            snapshot.h1 = [" ".join(parser.h1_parts).strip()] if parser.h1_parts else []
            snapshot.h2s = parser.h2s
            snapshot.images = parser.images
            snapshot.links = parser.links
            snapshot.body_text = " ".join(parser.body_parts).strip()
        return snapshot

    # -- robots.txt ----------------------------------------------------------

    def fetch_robots(self, base_url: str | None = None) -> "RobotsRules":
        base = (base_url or self.config.static_site_url).rstrip("/")
        self.validate_url(f"{base}/robots.txt")
        response = self.http.get(f"{base}/robots.txt")
        if response.status_code != 200:
            return RobotsRules(base=base, raw="", disallow=[], sitemaps=[])
        return RobotsRules.parse(base, response.text)

    def close(self) -> None:
        self.http.close()
        if self._own_store is not None:
            self._own_store.close()
            self._own_store = None

    def __enter__(self) -> "StaticSiteClient":
        return self

    def __exit__(self, *exc: Any) -> None:
        self.close()


class RobotsRules:
    """Minimal robots.txt parser: Disallow rules + Sitemap directives."""

    def __init__(self, *, base: str, raw: str, disallow: list[str], sitemaps: list[str]):
        self.base = base
        self.raw = raw
        self.disallow = disallow
        self.sitemaps = sitemaps

    @classmethod
    def parse(cls, base: str, raw: str) -> "RobotsRules":
        disallow: list[str] = []
        sitemaps: list[str] = []
        for line in raw.splitlines():
            line = line.strip()
            if not line or line.startswith("#") or ":" not in line:
                continue
            field, _, value = line.partition(":")
            field = field.strip().lower()
            value = value.strip()
            if field == "disallow" and value:
                disallow.append(value)
            elif field == "sitemap":
                sitemaps.append(value)
        return cls(base=base, raw=raw, disallow=disallow, sitemaps=sitemaps)

    def is_blocked(self, url: str) -> bool:
        path = urlparse(url).path
        for rule in self.disallow:
            if rule == "/" and path != "/":
                return True
            if rule and path.startswith(rule):
                return True
        return False


def _parse_sitemap_urls(xml_text: str, *, is_index: bool) -> list[str]:
    return [loc for loc, _ in _parse_sitemap_entries(xml_text, is_index=is_index)]


def _parse_sitemap_entries(xml_text: str, *, is_index: bool) -> list[tuple[str, str]]:
    """Retorna (loc, lastmod) de um <sitemapindex> ou <urlset>."""
    try:
        root = ET.fromstring(xml_text)
    except ET.ParseError as exc:
        raise ConnectorError(f"invalid sitemap XML: {exc}") from exc
    tag = f"{_SITEMAP_NS}sitemap" if is_index else f"{_SITEMAP_NS}url"
    entries: list[tuple[str, str]] = []
    for node in root.iter(tag):
        loc = node.find(f"{_SITEMAP_NS}loc")
        lastmod = node.find(f"{_SITEMAP_NS}lastmod")
        if loc is not None and loc.text and loc.text.strip():
            entries.append((loc.text.strip(), (lastmod.text or "").strip() if lastmod is not None else ""))
    return entries
