"use client";

import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import type { ApiError, TitleImpact, TitleImpactWindow } from "@/lib/api";
import { api } from "@/lib/api";
import { Card } from "@/design-system/card";

type WindowKey = "7" | "28" | "90";
type TimelinePoint = TitleImpactWindow["timeline"][number];
type LinePoint = { date: string; value: number | null };

const integer = new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 0 });
const decimal = new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 1 });

export function TitleImpactWidget() {
  const [windowKey, setWindowKey] = useState<WindowKey>("28");
  const query = useQuery({ queryKey: ["dashboard", "title-impact"], queryFn: () => api.get<{ title_impact: TitleImpact }>("/dashboard/title-impact") });
  if (query.isLoading) return <Card title="Impacto acumulado das otimizações de título"><p className="text-sm text-[var(--muted)]">Carregando coortes de medição…</p></Card>;
  if (query.isError) return <Card title="Impacto acumulado das otimizações de título"><p className="text-sm text-[var(--danger)]">{(query.error as ApiError).message}</p></Card>;
  const impact = query.data?.title_impact;
  if (!impact) return <Card title="Impacto acumulado das otimizações de título"><p className="text-sm text-[var(--muted)]">O resumo de títulos não está disponível.</p></Card>;
  const selected = impact.windows[windowKey];

  return <Card className="p-5" title="Impacto acumulado das otimizações de título">
    <div role="tablist" aria-label="Janela de medição de títulos" className="flex w-fit rounded-md border border-[var(--border)] p-0.5">
      {(["7", "28", "90"] as WindowKey[]).map((key) => <button key={key} role="tab" aria-selected={windowKey === key} onClick={() => setWindowKey(key)} className={`rounded-[5px] px-3 py-1.5 text-sm font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--primary)] ${windowKey === key ? "bg-[var(--primary-soft)] text-[var(--primary)]" : "text-[var(--muted)] hover:text-[var(--foreground)]"}`}>{key}d</button>)}
    </div>
    <section aria-label="Resumo de títulos" className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <MetricCard value={integer.format(impact.titles_modified_total)} label="Títulos modificados" detail={periodChange(impact.titles_modified_period, impact.previous_period_delta)} />
      <MetricCard value={selected.observed.clicks.delta_percent === null ? "Sem dados" : signedPercent(selected.observed.clicks.delta_percent)} label="Aumento de cliques" detail={selected.observed.clicks.delta === null ? "Sem baseline comparável" : `${signedNumber(selected.observed.clicks.delta)} no Google`} />
      <MetricCard value={selected.outcomes.improvement_rate === null || selected.outcomes.improvement_rate === undefined ? "Sem dados" : `${decimal.format(selected.outcomes.improvement_rate)}%`} label="Títulos melhoraram" detail={`${integer.format(selected.outcomes.improved ?? 0)} de ${integer.format(selected.measured_titles)} mensurados`} />
      <MetricCard value={integer.format(selected.measured_titles)} label={`Já mensurados (≥ ${selected.days} dias)`} detail={`${share(selected.measured_titles, impact.titles_modified_total)} do total`} />
    </section>
    <section className="mt-4 rounded-[9px] border border-[var(--border)] bg-[var(--surface)] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Impacto das otimizações de título</h2><p className="text-sm text-[var(--muted)]">Comparativo de performance no Google após as modificações</p></div><span className="rounded-md border border-[var(--border)] px-3 py-1 text-sm font-medium">Cliques</span></div><div className="mt-3 grid gap-4 xl:grid-cols-[minmax(0,1fr)_18rem]"><ForecastResultChart timeline={selected.timeline} /><ResultPanel selected={selected} adjusted={impact.benchmark.adjusted_click_delta_percent} /></div></section>
    <div className="mt-4 grid gap-4 xl:grid-cols-2"><AccumulatedImpactChart titles={impact.modification_timeline ?? []} timeline={selected.timeline} /><OutcomeDonut selected={selected} /></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-2"><ForecastObserved selected={selected} /><MeasurementPipeline impact={impact} /></div>
    <p className="mt-4 text-xs text-[var(--muted)]">{selected.limitations}</p>
  </Card>;
}

function ForecastResultChart({ timeline }: { timeline: TimelinePoint[] }) {
  const points = timeline.filter((point) => point.observed_index !== null || point.forecast_index !== null || point.benchmark_index !== null);
  if (!points.length) return <EmptyLineChart title="Previsto × resultado real" xLabels={months(timeline)} text="Ainda não há resultado comparável nesta janela." />;
  return <LineChart title="Índice de performance — base = 100" xLabels={points.map((point) => shortMonth(point.date))} series={[
    { label: "Resultado observado Google", values: points.map((point) => point.observed_index), tone: "primary" },
    { label: "Previsão do SEO Agent", values: points.map((point) => point.forecast_index), tone: "info", dash: "5 4" },
    { label: "Tendência orgânica geral do site", values: points.map((point) => point.benchmark_index), tone: "muted", dash: "2 4" },
  ]} baseline={100} valueLabel={(value) => `${value >= 100 ? "+" : ""}${Math.round(value - 100)}%`} />;
}

function AccumulatedImpactChart({ titles, timeline }: { titles: TitleImpact["modification_timeline"]; timeline: TimelinePoint[] }) { const clicks = cumulativeClickSeries(timeline); if (!titles.length) return <EmptyLineChart title="Títulos modificados × impacto acumulado" xLabels={[]} text="Ainda não existem ações de título executadas." />; const clickByDate = new Map(clicks.map((point) => [point.date, point.value])); const data = titles.map((point) => ({ ...point, clicks: clickByDate.get(point.date) ?? null })); const maxTitles = Math.max(...data.map((point) => point.titles_modified_cumulative), 1); const clickValues = data.map((point) => point.clicks).filter((value): value is number => value !== null); const maxClicks = Math.max(...clickValues, 1); const px = (index: number) => data.length === 1 ? 220 : 45 + index * 350 / (data.length - 1); const clickY = (value: number) => 132 - value / maxClicks * 94; const clickPath = data.map((point, index) => point.clicks === null ? "" : `${px(index)},${clickY(point.clicks)}`).filter(Boolean).join(" "); return <section className="rounded-[9px] border border-[var(--border)] bg-[var(--surface)] p-4"><h2 className="font-semibold">Títulos modificados × impacto acumulado</h2><p className="text-sm text-[var(--muted)]">Evolução de títulos otimizados e cliques ganhos no Google</p><svg viewBox="0 0 420 170" className="mt-3 h-56 w-full" role="img" aria-label="Títulos modificados acumulados e cliques ganhos acumulados"><line x1="40" y1="132" x2="400" y2="132" stroke="var(--border)" /><line x1="40" y1="28" x2="40" y2="132" stroke="var(--border)" />{data.map((point, index) => <g key={point.date}><rect x={px(index) - 12} y={132 - point.titles_modified_cumulative / maxTitles * 94} width="24" height={point.titles_modified_cumulative / maxTitles * 94} rx="3" fill="var(--primary)" /><text x={px(index)} y="153" textAnchor="middle" fill="var(--muted)" fontSize="10">{shortMonth(point.date)}</text></g>)}{clickPath && <><polyline points={clickPath} fill="none" stroke="var(--success)" strokeWidth="2.5" />{data.map((point, index) => point.clicks === null ? null : <circle key={`click-${point.date}`} cx={px(index)} cy={clickY(point.clicks)} r="3" fill="var(--success)" />)}</>}<text x="32" y="136" textAnchor="end" fill="var(--muted)" fontSize="10">0</text><text x="32" y="32" textAnchor="end" fill="var(--muted)" fontSize="10">{integer.format(maxTitles)}</text></svg><div className="mt-1 flex flex-wrap gap-3 text-xs text-[var(--muted)]"><span><i className="mr-1 inline-block h-2 w-2 rounded-sm bg-[var(--primary)]" />Títulos modificados (acumulado)</span><span><i className="mr-1 inline-block h-0.5 w-4 bg-[var(--success)]" />Cliques adicionais (acumulado)</span></div></section>; }
function OutcomeDonut({ selected }: { selected: TitleImpactWindow }) { const rows = [["Melhoraram", selected.outcomes.improved ?? 0, "success"], ["Neutros", selected.outcomes.neutral ?? 0, "info"], ["Pioraram", selected.outcomes.worsened ?? 0, "warning"], ["Dados insuficientes", selected.outcomes.insufficient_data ?? 0, "muted"]] as const; const total = rows.reduce((sum, [, value]) => sum + value, 0); let offset = 0; return <section className="rounded-[9px] border border-[var(--border)] bg-[var(--surface)] p-4"><h2 className="font-semibold">Resultado das otimizações (≥ {selected.days} dias)</h2><p className="text-sm text-[var(--muted)]">Distribuição dos títulos modificados com dados no Google</p><div className="mt-3 flex flex-wrap items-center gap-5"><svg viewBox="0 0 120 120" className="h-36 w-36" role="img" aria-label={`${integer.format(total)} títulos mensurados`}>{total ? rows.map(([label, value, tone]) => { const part = value / total * 100; const circle = <circle key={label} cx="60" cy="60" r="42" fill="none" stroke={`var(--${tone})`} strokeWidth="18" strokeDasharray={`${part} ${100 - part}`} strokeDashoffset={-offset} pathLength="100" transform="rotate(-90 60 60)" />; offset += part; return circle; }) : <circle cx="60" cy="60" r="42" fill="none" stroke="var(--border)" strokeWidth="18" />}</svg><div className="min-w-44 flex-1 space-y-2">{rows.map(([label, value, tone]) => <div key={label} className="flex items-center justify-between gap-3 text-sm"><span><i className="mr-2 inline-block h-2.5 w-2.5 rounded-full" style={{ backgroundColor: `var(--${tone})` }} />{label}</span><span className="tabular-nums">{integer.format(value)} · {share(value, total)}</span></div>)}</div></div></section>; }
function ForecastObserved({ selected }: { selected: TitleImpactWindow }) { const forecast = selected.forecast.clicks_delta; const observed = selected.observed.clicks.delta; return <section className="rounded-[9px] border border-[var(--border)] bg-[var(--surface)] p-4"><h2 className="font-semibold">Previsto × observado</h2><p className="text-sm text-[var(--muted)]">Comparação entre ganho estimado e resultado real do Google</p><div className="mt-3 grid gap-2 sm:grid-cols-3"><MiniMetric label="Cliques previstos" value={forecast === null ? "—" : signedNumber(forecast)} detail={selected.forecast.clicks_delta_percent === null ? "Sem previsão" : signedPercent(selected.forecast.clicks_delta_percent)} /><MiniMetric label="Cliques observados" value={observed === null ? "—" : signedNumber(observed)} detail={selected.observed.clicks.delta_percent === null ? "Sem dados" : signedPercent(selected.observed.clicks.delta_percent)} /><MiniMetric label="Resultado acima do previsto" value={forecast === null || observed === null ? "—" : signedPercent((observed - forecast) / Math.max(Math.abs(forecast), 1) * 100)} detail="Comparação da mesma janela" /></div></section>; }
function ResultPanel({ selected, adjusted }: { selected: TitleImpactWindow; adjusted: number | null }) { return <aside className="rounded-[8px] border border-[var(--border)] bg-[var(--surface-raised)] p-3"><h3 className="font-medium">Resultados (≥ {selected.days} dias)</h3><div className="mt-3 border-t border-[var(--border)] pt-3"><p className="text-xs text-[var(--muted)]">Cliques</p><div className="mt-1 grid grid-cols-2 gap-2"><div><span className="text-xs text-[var(--muted)]">Antes</span><strong className="block tabular-nums">{selected.observed.clicks.before === null ? "—" : integer.format(selected.observed.clicks.before)}</strong></div><div><span className="text-xs text-[var(--muted)]">Depois</span><strong className="block tabular-nums">{selected.observed.clicks.after === null ? "—" : integer.format(selected.observed.clicks.after)}</strong></div></div></div><div className="mt-3 border-t border-[var(--border)] pt-3"><p className="text-xs text-[var(--muted)]">Impacto ajustado</p><strong className="mt-1 block text-xl text-[var(--success)]">{adjusted === null ? "Ainda não mensurável" : signedPercent(adjusted)}</strong><p className="mt-1 text-xs text-[var(--muted)]">acima da tendência orgânica</p></div></aside>; }
function MeasurementPipeline({ impact }: { impact: TitleImpact }) { const stages = [["Títulos modificados", impact.titles_modified_total], ["≥ 7 dias", impact.measurable_7d], ["≥ 28 dias", impact.measurable_28d], ["≥ 90 dias", impact.measurable_90d], ["Aguardando dados", impact.awaiting_measurement]]; return <section className="rounded-[9px] border border-[var(--border)] bg-[var(--surface)] p-4"><h2 className="font-semibold">Pipeline de medição</h2><p className="text-sm text-[var(--muted)]">Quantos títulos já podem ser considerados nos resultados</p><ol className="mt-4 flex flex-wrap items-end justify-between gap-2">{stages.map(([label, value], index) => <li key={label} className="flex min-w-20 flex-1 items-end gap-2"><div className="flex-1 text-center"><strong className="block tabular-nums">{integer.format(value as number)}</strong><div className="mx-auto mt-1 h-12 w-9 rounded-t bg-[var(--primary)]" style={{ opacity: Math.max(.35, 1 - index * .12) }} /><span className="mt-1 block text-xs text-[var(--muted)]">{label}</span></div>{index < stages.length - 1 && <span className="pb-8 text-[var(--muted)]" aria-hidden="true">→</span>}</li>)}</ol></section>; }
function MiniMetric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-[7px] border border-[var(--border)] p-3"><span className="block text-xs text-[var(--muted)]">{label}</span><strong className="mt-1 block text-lg tabular-nums">{value}</strong><span className="text-xs text-[var(--success)]">{detail}</span></div>; }

type Series = { label: string; values: Array<number | null>; tone: "primary" | "info" | "muted"; dash?: string };
function LineChart({ title, subtitle, xLabels, series, baseline = 0, valueLabel }: { title: string; subtitle?: string; xLabels: string[]; series: Series[]; baseline?: number; valueLabel: (value: number) => string }) {
  const values = series.flatMap((item) => item.values).filter((value): value is number => value !== null);
  const lower = Math.min(baseline, ...values); const upper = Math.max(baseline + 1, ...values); const range = Math.max(1, upper - lower);
  const y = (value: number) => 128 - (value - lower) / range * 100;
  const coords = (values: Array<number | null>) => values.map((value, index) => value === null ? "" : `${x(index, values.length)},${y(value)}`).filter(Boolean).join(" ");
  return <section className="rounded-[8px] border border-[var(--border)] p-3"><div><h3 className="font-semibold">{title}</h3>{subtitle && <p className="text-xs text-[var(--muted)]">{subtitle}</p>}</div><Legend series={series} /><svg viewBox="0 0 420 164" className="mt-2 h-52 w-full" role="img" aria-label={title}><Axes lower={lower} upper={upper} valueLabel={valueLabel} />{series.map((item) => <g key={item.label}><polyline points={coords(item.values)} fill="none" stroke={color(item.tone)} strokeWidth="2.5" strokeDasharray={item.dash} />{item.values.map((value, index) => value === null ? null : <circle key={`${item.label}-${index}`} cx={x(index, item.values.length)} cy={y(value)} r="3" fill={color(item.tone)} />)}</g>)}{xLabels.map((label, index) => <text key={`${label}-${index}`} x={x(index, xLabels.length)} y="153" textAnchor="middle" fill="var(--muted)" fontSize="10">{label}</text>)}</svg></section>;
}

function EmptyLineChart({ title, xLabels, text, marker = false }: { title: string; xLabels: string[]; text: string; marker?: boolean }) {
  return <section className="rounded-[8px] border border-[var(--border)] p-3"><h3 className="font-semibold">{title}</h3><svg viewBox="0 0 420 164" className="mt-2 h-52 w-full" role="img" aria-label={`${title}: dados insuficientes`}><Axes lower={95} upper={130} valueLabel={(value) => Math.round(value).toString()} />{marker && <><line x1={x(2, 6)} y1="28" x2={x(2, 6)} y2="128" stroke="var(--muted)" strokeDasharray="2 4" /><circle cx={x(2, 6)} cy="128" r="3" fill="var(--foreground)" /><text x={x(2, 6)} y="143" textAnchor="middle" fill="var(--muted)" fontSize="10">alteração</text></>}{xLabels.map((label, index) => <text key={`${label}-${index}`} x={x(index, xLabels.length)} y="153" textAnchor="middle" fill="var(--muted)" fontSize="10">{label}</text>)}<text x="210" y="82" textAnchor="middle" fill="var(--muted)" fontSize="11">{text}</text></svg></section>;
}

function Axes({ lower, upper, valueLabel }: { lower: number; upper: number; valueLabel: (value: number) => string }) { const middle = (lower + upper) / 2; return <><line x1="40" y1="128" x2="400" y2="128" stroke="var(--border)" /><line x1="40" y1="28" x2="40" y2="128" stroke="var(--border)" />{[lower, middle, upper].map((value, index) => <g key={index}><line x1="40" y1={128 - index * 50} x2="400" y2={128 - index * 50} stroke="var(--border)" strokeDasharray={index === 0 ? undefined : "3 4"} /><text x="32" y={132 - index * 50} textAnchor="end" fill="var(--muted)" fontSize="10">{valueLabel(value)}</text></g>)}</>; }
function Legend({ series }: { series: Series[] }) { return <div className="mt-2 flex flex-wrap gap-3 text-xs text-[var(--muted)]">{series.map((item) => <span key={item.label}><i className={`mr-1 inline-block h-px w-4 align-middle ${item.dash ? "border-t border-dashed" : ""}`} style={{ backgroundColor: item.dash ? undefined : `var(--${item.tone})`, borderColor: `var(--${item.tone})` }} />{item.label}</span>)}</div>; }
function MetricCard({ value, label, detail }: { value: string; label: string; detail: string }) { return <div className="rounded-[8px] border border-[var(--border)] bg-[var(--surface-raised)] p-3"><strong className="text-xl tabular-nums">{value}</strong><span className="mt-1 block text-xs font-medium">{label}</span><span className="mt-1 block text-xs text-[var(--muted)]">{detail}</span></div>; }
export function cumulativeClickSeries(timeline: TimelinePoint[]): LinePoint[] { let total = 0; return timeline.map((point) => { const delta = point.observed_clicks_delta; if (delta !== null && delta !== undefined) total += delta; return { date: point.date, value: delta === null || delta === undefined ? null : total }; }); }
function color(tone: Series["tone"]) { return `var(--${tone})`; }
function x(index: number, total: number) { return total <= 1 ? 220 : 40 + index * 360 / (total - 1); }
function months(timeline: TimelinePoint[]) { return timeline.map((point) => shortMonth(point.date)); }
function shortMonth(value: string) { const date = new Date(`${value}-01T12:00:00`); return Number.isNaN(date.valueOf()) ? value : new Intl.DateTimeFormat("pt-BR", { month: "short" }).format(date); }
function compactNumber(value: number) { return new Intl.NumberFormat("pt-BR", { notation: "compact", maximumFractionDigits: 1 }).format(value); }
function signedNumber(value: number) { return `${value > 0 ? "+" : ""}${decimal.format(value)}`; }
function signedPercent(value: number) { return `${value > 0 ? "+" : ""}${decimal.format(value)}%`; }
function share(value: number, total: number) { return total ? `${decimal.format(value / total * 100)}%` : "0%"; }
function periodChange(current: number, delta: number | null) { return delta === null ? `${integer.format(current)} nos últimos 28 dias` : `${delta >= 0 ? "+" : ""}${integer.format(delta)} últimos 28d`; }
